FROM rust:1.44-stretch as builder

RUN USER=root cargo new --lib users
WORKDIR ./users
COPY ./Cargo.toml ./Cargo.toml
RUN cargo build --release --lib
RUN rm src/*.rs

ADD . ./

RUN rm ./target/release/deps/users*
RUN cargo build --release

FROM debian:stretch-slim
ARG APP=/usr/src/app

ENV TZ=Etc/UTC \
    RUN_MODE=development \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

COPY --from=builder /users/target/release/service ${APP}/service
COPY --from=builder /users/config ${APP}/config
COPY --from=builder /users/users.json ${APP}/users.json

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./service"]
