SET CLIENT_MIN_MESSAGES TO WARNING;
SET CLIENT_ENCODING = 'UTF8';
DROP SCHEMA IF EXISTS main CASCADE;
SET CLIENT_MIN_MESSAGES TO INFO;
SET CLIENT_ENCODING = 'UTF8';
CREATE SCHEMA main;
-- SET SEARCH_PATH = main;
CREATE EXTENSION pg_trgm SCHEMA main;
CREATE EXTENSION pgcrypto SCHEMA main;
CREATE TABLE main.users (
  id UUID PRIMARY KEY DEFAULT main.gen_random_uuid(),
  username VARCHAR(128) NOT NULL UNIQUE CHECK (username <> ''),
  email VARCHAR(128) NOT NULL CHECK (email <> ''),
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
